version: "3.8"
services:
  moodcast-backend:
    build: .
    container_name: moodcast-backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7-alpine
    container_name: moodcast-redis
    ports:
      - "6380:6379"
    restart: always
